### PR TITLE
Several refinements

### PR DESCRIPTION
**Pull request by sharpninja**
| Flag | Purpose |
|------|---------|
| -Verbose (-v) | Output the lines with problems both as they appear and with the unicode character tag displayed. |
| -ESC (-e) | Exclude escape character (\u7F) |
| -BOM (-b) | Exclude Unicode Byte-order Marks (\uFEFF) |

If the first parameter is a valid folder, it will be used instead of prompting the user for a folder to scan.

### CODE REVIEW

**Review by jespanag — APPROVED** [review]
Very interesting, thanks for the contribution!

**Comment by sharpninja** [comment]
Will this be making it to Nuget soon?

**Comment by jespanag** [comment]
Yes, nuget it's processing package rigth now!

**Comment by sharpninja** [comment]
Please retract this article on DEV.TO and the post on Medium as well:  https://dev.to/dotnetsafer/10-c-mistakes-that-damage-your-code-how-to-avoid-them-225j.  If you don't then I revoke the license to further distribute the code in this PR.

**Pull request merged**
